# This dockerfile is inspired by https://github.com/motiz88/corenlp-docker/blob/master/Dockerfile
#https://github.com/NLPbox/stanford-corenlp-docker/blob/master/Dockerfile

FROM alpine:3.10 as builder

RUN apk update && apk add wget unzip 

WORKDIR /opt
RUN wget https://github.com/stanfordnlp/CoreNLP/archive/v3.9.2.zip && \
    unzip v*.zip && \
    mv $(ls -d CoreNLP-*/) corenlp && rm *.zip

WORKDIR /opt/corenlp
RUN wget http://nlp.stanford.edu/software/stanford-german-corenlp-models-current.jar

FROM alpine:3.10

RUN apk update && apk add openjdk11-jre-headless

WORKDIR /opt/corenlp

COPY --from=builder /opt/corenlp .

ENV PORT 9000
EXPOSE $PORT

CMD java -Xmx2g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000
